---
   - name: install epel
     yum: name=epel-release state=latest

   - name: install nginx
     yum: name=nginx state=present

   - name: open firewall port
     firewalld:
       service: http
       immediate: true
       permanent: true
       state: enabled

   - name: set content directory group/permissions 
     file:
       path: /var/www/html/{{ project_name }}
       owner: nginx
       group: nginx
       state: directory
       mode: u=rwx,g=rwx,o=rx,g+s

   - name: create default page content
     copy:
       content: "Welcome to {{ ansible_fqdn }} on {{ ansible_default_ipv4.address }}"
       dest: /var/www/html/{{ project_name }}/index.html
       owner: nginx
       group: nginx
       mode: 0644

   - name: nginx config
     template:
       src: nginx_def.conf
       dest: /etc/nginx/conf.d/default.conf
       owner: nginx
       group: nginx
       mode: 0644

   - name: nginx base config
     copy:
       src: nginx.conf.base
       dest: /etc/nginx/nginx.conf
       owner: nginx
       group: nginx
       mode: 0644

   - name: start and enable nginx
     service: name=nginx enabled=yes state=started

   - name: install php
     yum: name=php state=present

   - name: install php-fpm
     yum: name=php-fpm state=present
 
   - name: php config
     copy:
       src: php.conf
       dest: /etc/php-fpm.d/www.conf
       owner: nginx
       group: nginx
       mode: 0644

   - name: php base config
     copy:
       src: php.conf.base
       dest: /etc/php-fpm.conf
       owner: nginx
       group: nginx
       mode: 0644

   - name: php test page
     copy:
       content: "<?php phpinfo(); ?>"
       dest: /var/www/html/{{ project_name }}/phpinfo.php
       owner: nginx
       group: nginx
       mode: 0644

   - name: php-fpm enable and start
     service: name=php-fpm enabled=yes state=started
