---
- name: add mysql repository
  yum: name=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm state=present

- name: install mysql
  yum: name=mysql state=present

- name: Install MySQL Server
  yum: name=mysql-server state=present

- name: Install MySQL-python, this is required for the task remove anonymous user
  yum: name=MySQL-python state=present

- name: Start MySQL Server and enable it
  service: name=mysqld state=started enabled=yes

- name: Remove Test database if it exist.
  mysql_db: name=test state=absent

- name: Remove All Anonymous User Accounts
  mysql_user: name='' host_all=yes state=absent

- name: Change root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_pass }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy mysql config
  template:
    src: my.cnf
    dest: /root/.my.cnf
    force: yes
    owner: root
    mode: 0600

- name: restart mysql
  service: name=mysqld state=restarted

- name: create db
  mysql_db: name={{ project_name }} collation=utf8_general_ci encoding=utf8 state=present

- name: create db user
  mysql_user: name={{ sql_username }} password={{ sql_password }} priv="{{ project_name }}.*:ALL"

